export const projects = [
  {
    title: "EasyHR - AI Recruiting Platform",
    subtitle: "End-to-End Recruiting & Onboarding Automation",
    problem: "Traditional recruiting processes require manual CV screening, skill extraction, and candidate communication, leading to 40+ hours/week wasted by HR teams and qualified candidates being overlooked.",
    solution: "Built an AI-powered recruiting workflow that automates CV import, skill extraction, candidate ranking with explainable scoring, ATS pipeline management, and onboarding checklists. Integrated OpenAI/Gemini APIs for HR summaries and interview question generation.",
    techStack: ["Next.js", "TypeScript", "FastAPI", "Python", "PostgreSQL", "Redis", "Celery", "S3", "OpenAI API", "Gemini API", "Docker"],
    impact: "Automated end-to-end recruiting • AI-powered skill extraction • Explainable candidate scoring • Onboarding automation",
    imageUrl: "/images/easyhr-thumbnail.jpg",
    githubUrl: "https://github.com/Nchotie-cliford/easyhr",
    category: "AI/ML" as const,
  },
  {
    title: "RKA-AI - Knowledge Assistant",
    subtitle: "RAG System with RBAC & Source Citations",
    problem: "Enterprise teams struggle to find information across scattered internal documents. Traditional search fails to provide contextual answers, and security concerns prevent AI adoption due to lack of access control and source transparency.",
    solution: "Developed a Retrieval-Augmented Generation (RAG) system with role-based access control (RBAC). Implements document pipeline (PDF/DOCX/HTML), chunking, embeddings, and vector search. Features audit logs, PII redaction, prompt injection defense, and always cites sources.",
    techStack: ["Next.js", "TypeScript", "Spring Boot", "Java", "PostgreSQL", "pgvector", "Redis", "S3", "OpenAI API", "Gemini API", "Docker"],
    impact: "RBAC for secure knowledge access • Source citations & snippets • PII redaction & audit logs • Prompt injection defense",
    imageUrl: "/images/rka-ai-thumbnail.jpg",
    githubUrl: "https://github.com/Nchotie-cliford/rka-ai",
    category: "AI/ML" as const,
  },
  {
    title: "UrlaubPilot - Smart Holiday Planner",
    subtitle: "Trip Planning with AI Itineraries & Video Recaps",
    problem: "Planning multi-destination trips is time-consuming, requiring hours of research across platforms. Travelers also lack tools to create shareable trip recaps for social media in vertical video formats (Reels/TikTok).",
    solution: "Created a full-stack travel planner that aggregates prices, scores optimal travel windows, generates AI-powered itineraries with recommendations and price alerts. Includes asynchronous video rendering pipeline using FFmpeg to create vertical recap videos from trip media.",
    techStack: ["Next.js", "TypeScript", "Spring Boot", "Java", "PostgreSQL", "Redis", "RabbitMQ", "S3", "FFmpeg", "Docker"],
    impact: "Price aggregation & scoring • AI itinerary generation • Vertical video recap studio • Async rendering pipeline",
    videoUrl: "/videos/urlaubpilot-demo.mp4",
    imageUrl: "/images/urlaubpilot-thumbnail.jpg",
    githubUrl: "https://github.com/Nchotie-cliford/urlaubpilot",
    liveUrl: "https://nchotie.xyz",
    category: "Fullstack" as const,
  },
];

export const experience = [
  {
    company: "Arvato Systems GmbH",
    role: "Werkstudent – IT Engineer (TenneT TSO)",
    period: "01/2024 – 12/2025",
    location: "Bayreuth, Germany",
    description: "Supporting critical IT infrastructure for TenneT, Germany's main electricity transmission system operator.",
    achievements: [
      "Handled 1st/2nd level support requests, resolving 95% of hardware/software issues within SLA for 1,000+ users",
      "Supported project management: tracking milestones, status reporting, maintaining IT asset data",
      "Maintained service availability for critical energy grid infrastructure systems",
    ],
    tech: ["IT Support", "Project Management Tools", "Hardware/Software Troubleshooting", "SLA Management"],
  },
  {
    company: "In-Reach UG & Co. KG",
    role: "Werkstudent – Junior Software Developer",
    period: "03/2023 – 12/2023",
    location: "Hof, Germany",
    description: "Full-stack development of web and mobile applications for internal and client projects.",
    achievements: [
      "Developed features for web applications in C#/.NET and Xamarin-based mobile app, improving usability for 200+ users",
      "Collaborated with stakeholders to refine requirements using agile methodologies",
      "Contributed to code reviews and quality assurance processes",
    ],
    tech: ["C#", ".NET", "Xamarin", "Agile Development", "Stakeholder Management"],
  },
  {
    company: "Universität Bayreuth",
    role: "Studentische Hilfskraft – ITS Laptop Support",
    period: "10/2022 – 10/2024",
    location: "Bayreuth, Germany (Hybrid)",
    description: "Technical support for university students and staff.",
    achievements: [
      "Resolved 1,000+ hardware/software support requests",
      "Contributed to ~25% increase in user satisfaction through efficient problem-solving",
      "Documented common issues and created knowledge base articles",
    ],
    tech: ["Windows", "macOS", "Linux", "Hardware Troubleshooting", "User Support"],
  },
  {
    company: "Africa Multiple Cluster of Excellence",
    role: "Wissenschaftliche Hilfskraft – Research Assistant",
    period: "01/2023 – 10/2023",
    location: "Universität Bayreuth",
    description: "Digital humanities project focusing on colonial archives.",
    achievements: [
      "Built project website and digital database for colonial archive research",
      "Analyzed data patterns using clustering algorithms (K-Means)",
      "Created dynamic reports and visualizations with Power BI for research teams",
    ],
    tech: ["Python", "Data Analysis", "Power BI", "Web Development", "Clustering Algorithms"],
  },
];
